# Generated by Django 5.0.4 on 2024-05-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_question_pub_date'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(through='quiz.QuizQuestion', to='question.question'),
        ),
    ]
