# Generated by Django 5.0.4 on 2024-05-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateQuiz', '0001_initial'),
        ('quiz', '0003_quizquestion_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='privateQuiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='privateQuiz.privatequiz'),
        ),
    ]
