# Generated by Django 5.0.4 on 2024-05-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
