# Generated by Django 5.0.4 on 2024-05-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
