# Generated by Django 5.0.4 on 2024-05-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatequiz',
            name='code',
            field=models.CharField(default='29d1aa884f3e4966bd939a7ea4068aca', max_length=5, unique=True),
        ),
    ]
