# Generated by Django 5.0.4 on 2024-05-14 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateQuiz', '0002_alter_privatequiz_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatequiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatequiz',
            name='code',
            field=models.CharField(default='e6a67b5505494d79bc254a5fb15832b6', max_length=5, unique=True),
        ),
    ]
