# Generated by Django 5.0.4 on 2024-05-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateQuiz', '0003_privatequiz_created_at_alter_privatequiz_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatequiz',
            name='name',
            field=models.CharField(default='Private', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatequiz',
            name='code',
            field=models.CharField(default='0210f69fa91a406086f18ef4596edd38', max_length=5, unique=True),
        ),
    ]
