# Generated by Django 5.0.4 on 2024-05-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateQuiz', '0004_privatequiz_name_alter_privatequiz_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatequiz',
            name='code',
            field=models.CharField(default='4a3662f6c83f4b7f928f0142bcd4dc34', max_length=5, unique=True),
        ),
    ]
