# Generated by Django 5.0.4 on 2024-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateQuiz', '0005_alter_privatequiz_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatequiz',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
